name: integration tests

on:
  push:
    branches-ignore: [master]
  workflow_dispatch:

jobs:
  integration-tests:
    strategy:
      matrix:
        node: [10, 12, 14, 16]
      fail-fast: false
    runs-on: ubuntu-latest
    # container: node:16-bullseye
    services:
      redis:
        image: redis
        ports: 6379/tcp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      # - name: Cache node modules
      #   id: cache-nodemodules
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: sudo apt-get install -y redis-server
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: npm run test:ci # TODO: add integration tests
